### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pedrocarmona** [ankane/hypershield#1]
- Creating a view makes the query slower. In postgres its possible to do column based access. Could be made smart enough to detect if it is required to  create a view in schema or just give permissions to the user on given columns.
- allow multiple users.
- manage users and schemas via migrations.
- have a schema.rb but for database access: would show the current config of the database - see which users have access to what.

**Comment by ankane** [comment]
Hey @pedrocarmona, thanks for the suggestions. It uses views instead of column privileges so you can do `SELECT *`. Not sure I follow the last 3 points, but sounds like it's related to managing database users. Can you elaborate?

**Comment by pedrocarmona** [comment]
In modern startups is quite normal to have multiple applications consuming the database.
- airflow
- blazer/google datastudio/tableau
- google spreasheets
...

The comodity of a simple database connection became even more obvious to me when heroku release the follower database. Some clicks and we have an isolated read-only copy of the database.
But still, we need to set permissions, via the master database.
Its a good practice to create a user per service, and at some point becomes hard to document the access, would be better if some file like db/schema would describe the access.

Would be nice to use rails migrations, to create external schemas, set permissions to only some tables/ or partial tables (hide columns). Some times even create special views (joins of tables) for some users.

In my opinion
- application user owns the data.
- other services can us the data if the application user allows them.

**Comment by ankane** [comment]
While I think it's outside the scope of this project, I agreed it'd be nice to have a way to manage users and privileges in code. I tried managing users with configuration management software (Ansible, Salt, etc) while writing [this post](https://tech.instacart.com/bootstrapping-postgres-users-cd594e5f28e9), but didn't find anything I really liked.

**Comment by pedrocarmona** [comment]
Thanks Andrew for post link, I also saw ansible postgres grant module and agree with you that is not perfect. Will do more investigation for a better way, or come up with one :).
