### ISSUE TITLE
Issue with fields starting with same characters

### ISSUE THREAD

**Issue by sharmaparesh** [ankane/hypershield#11]
Looks like there is a bug if there are multiple fields starting with same characters and we want to *hide* one of them:

* This hides both `email` and `email_permission` ([reference](https://github.com/ankane/hypershield/blob/master/lib/hypershield.rb#L49)).
    ```ruby
    # table: customers
    # fields: name, email, email_permission

    Hypershield.schemas = { hypershield: { hide: ['email'] } }
    ```

* I can make it work with, and I wonder if this is the intended behaviour?
    ```ruby
    Hypershield.schemas = { hypershield: { hide: ['email'] , show: ['email_permission']} }
    ```

**Comment by ankane** [comment]
Hi @sharmaparesh, that's the intended behavior.
