### ISSUE TITLE
Per table columns hiding

### ISSUE THREAD

**Issue by rhymes** [ankane/hypershield#8]
Is there a way to selectively hide a column name which might contain sensitive data in one table but keep it shown from a different table?

For example: `notes.content` might be hidden but `orders.content` should be kept shown.

I glanced trough the code but it doesn't seem like the filter can do that.

Thank you!

**Comment by ankane** [comment]
Hi @rhymes, you can use `table.column` with the `show` and `hide` options.

**Comment by rhymes** [comment]
@ankane sorry! I should have double checked the README https://github.com/ankane/hypershield#configuration

Closing this and going to apply the change to the Hypershield configuration.

Great tool!
